const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
$('.menu').addEventListener('click',e=>{const n=$('#nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
const form=$('#intakeForm');let page=1;const next=$('#nextBtn'),prev=$('#prevBtn'),print=$('#printBtn');
function vals(){const fd=new FormData(form),o=Object.fromEntries(fd);o.outputs=fd.getAll('outputs');return o}
function renderBrief(){const o=vals(), esc=s=>(s||'Not provided').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));$('#briefPreview').innerHTML=`<h2>${esc(o.startup)} Challenge Brief</h2><dl><dt>Industry</dt><dd>${esc(o.industry)}</dd><dt>Stage</dt><dd>${esc(o.stage)}</dd><dt>Problem</dt><dd>${esc(o.problem)}</dd><dt>Customer</dt><dd>${esc(o.customer)}</dd><dt>Decision</dt><dd>${esc(o.decision)}</dd><dt>Why now</dt><dd>${esc(o.urgency)}</dd><dt>Desired outputs</dt><dd>${o.outputs.length?o.outputs.map(esc).join(', '):'Not selected'}</dd><dt>Available evidence</dt><dd>${esc(o.data)}</dd><dt>Confidentiality</dt><dd>${esc(o.confidentiality)}</dd><dt>Founder cadence</dt><dd>${esc(o.availability)}</dd><dt>Success</dt><dd>${esc(o.success)}</dd></dl>`}
function showPage(n){page=n;$$('fieldset[data-page]').forEach(f=>{f.hidden=+f.dataset.page!==page});$$('.form-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===page));prev.hidden=page===1;next.hidden=page===5;print.hidden=page!==5;if(page===5)renderBrief();form.scrollIntoView({behavior:'smooth',block:'center'})}
next.onclick=()=>{const fs=$(`fieldset[data-page="${page}"]`);if(![...fs.querySelectorAll('[required]')].every(x=>x.reportValidity()))return;showPage(Math.min(5,page+1))};prev.onclick=()=>showPage(page-1);print.onclick=()=>window.print();
$('#saveBtn').onclick=()=>{localStorage.setItem('ssl-intake',JSON.stringify(vals()));toast('Draft saved in this browser')};$('#clearBtn').onclick=()=>{form.reset();localStorage.removeItem('ssl-intake');showPage(1);toast('Draft cleared')};
const saved=localStorage.getItem('ssl-intake');if(saved){try{const o=JSON.parse(saved);Object.entries(o).forEach(([k,v])=>{if(k==='outputs')v.forEach(val=>{const x=$(`input[name="outputs"][value="${CSS.escape(val)}"]`);if(x)x.checked=true});else{const x=form.elements[k];if(x)x.value=v}});toast('Browser draft restored')}catch(e){}}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function calc(){const rev=+$('#revenue').value||0,m=(+$('#margin').value||0)/100,f=+$('#fixed').value||0,cash=+$('#cash').value||0,g=(+$('#growth').value||0)/100;const cont=rev*m,burn=Math.max(0,f-cont),be=m>0?f/m:0,runway=burn>0?cash/burn:Infinity;$('#contribution').textContent=money(cont);$('#burn').textContent=money(burn);$('#breakeven').textContent=money(be);$('#runway').textContent=Number.isFinite(runway)?runway.toFixed(1)+' months':'Cash generative';let bal=cash,r=rev,x=[0],y=[cash];for(let i=1;i<=18;i++){r*=1+g;bal+=r*m-f;x.push(i);y.push(Math.max(0,bal))}if(window.Plotly)Plotly.react('runwayChart',[{x,y,mode:'lines+markers',line:{color:'#07563e',width:4},fill:'tozeroy',fillcolor:'rgba(7,86,62,.12)'}],{title:'18-Month Cash Scenario',margin:{t:50,r:25,b:45,l:70},xaxis:{title:'Month'},yaxis:{title:'Cash balance ($)'},paper_bgcolor:'#fff',plot_bgcolor:'#fff',font:{family:'Inter, sans-serif'}},{displayModeBar:false,responsive:true})}
$$('#calcForm input').forEach(i=>i.addEventListener('input',calc));window.addEventListener('load',calc);
let sprints=[],tools=[],opps=[];function sprintRender(filter='all'){$('#sprintCards').innerHTML=sprints.filter(x=>filter==='all'||x.stage===filter).map(x=>`<article class="data-card"><span class="tag">${x.stage}</span><h3>${x.title}</h3><p>${x.challenge}</p><footer><span>${x.output}</span><b>${x.health}</b></footer></article>`).join('')};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');sprintRender(b.dataset.filter)});
function toolRender(){const q=$('#toolSearch').value.toLowerCase(),a=$('#toolAudience').value;$('#toolCards').innerHTML=tools.filter(x=>(a==='all'||x.audience.includes(a))&&(x.title+' '+x.description).toLowerCase().includes(q)).map(x=>`<article class="data-card"><span class="tag">${x.type}</span><h3>${x.title}</h3><p>${x.description}</p><footer><span>${x.audience.join(' · ')}</span><b>Prototype</b></footer></article>`).join('')};$('#toolSearch').oninput=toolRender;$('#toolAudience').onchange=toolRender;
Promise.all(['data/sprints.json','data/toolkit.json','data/opportunities.json'].map(u=>fetch(u).then(r=>r.json()))).then(([a,b,c])=>{sprints=a;tools=b;opps=c;sprintRender();toolRender();$('#opportunityCards').innerHTML=opps.map(x=>`<article class="data-card"><span class="tag">${x.commitment}</span><h3>${x.role}</h3><p>${x.description}</p><footer><span>${x.skills.join(' · ')}</span><b>${x.status}</b></footer></article>`).join('')}).catch(()=>toast('Demo data could not be loaded'));
